fos_user:
    db_driver: orm
    firewall_name: main
    user_class: UserBundle\Entity\User
    registration:
        confirmation:
            enabled: false
    service:                               # this lines
        mailer: fos_user.mailer.twig_swift # this lines
    from_email:
        address:        marmodesignpage@gmail.com
        sender_name:    Marmo Design
