user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

back:
    resource: "@BackBundle/Resources/config/routing.yml"
    prefix:   /admin

front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

app:
    resource: '@AppBundle/Controller/'
    type: annotation


