# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:


    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        UserBundle\Bundle\Entity\User: bcrypt


    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            user_checker: security.user_checker
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                require_previous_session: false


                # NEW BITS
                # the login form will POST here on submit
                # the default value would be /login_check
                check_path: fos_user_security_check

                # the user is redirected here when they need to log in
                # the default would be /login
                login_path: fos_user_security_login

                # We will fix this shortly, but for now, the default
                # would be '/', but we would need it to be e.g.
                # /en/
                default_target_path: /fr/admin

            logout:
                path: fos_user_security_logout
                target: fos_user_security_login
            anonymous:    true
            logout_on_user_change: true
            remember_me:
                secret: '%secret%'

    access_control:
    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ./register, role: ROLE_USER }
    - { path: ./admin/, role: ROLE_USER }
